#@TYPE: Machine
#@NAME: yald x86_64
#@DESCRIPTION: Machine configuration for yald x86_64 (64-bit) PCs and servers.

require conf/machine/include/x86/tune-x86-64-v3.inc
require conf/machine/include/genericx86-common.inc

MACHINEOVERRIDES =. "genericx86-64:"

MACHINE_FEATURES:remove = "alsa"
MACHINE_FEATURES:remove = "wifi"

#For runqemu
QB_SYSTEM_NAME = "qemu-system-x86_64"
QB_MEM = "-m 2G"
QB_OPT_APPEND:append = " -device intel-iommu,intremap=on -device edu"
QB_KERNEL_CMDLINE_APPEND:append = " vfio-pci.ids=1234:11e8"
IMAGE_FSTYPES += "ext4.zst"
