require conf/distro/poky.conf

DISTRO = "yald"
DISTRO_NAME = "yald (Yet Another Linux Distro)"

SDK_VENDOR = "-yaldsdk"
TARGET_VENDOR = "-yald"

DISTRO_FEATURES:remove = "alsa bluetooth ext2 pcmcia 3g nfc x11 opengl ptest wayland pulseaudio vulkan sysvinit wifi"

INIT_MANAGER = "systemd"
EFI_PROVIDER = "grub-efi"

INHERIT += "image-buildinfo"

require conf/distro/include/cve-extra-exclusions.inc

# Wrynose default is 6.18.x
# PREFERRED_VERSION_linux-yocto = "6.18%"
