version: 2.1

jobs:
  build-intel:
    docker:
      - image: crops/yocto:fedora-40-base
    steps:
      - checkout
      - run:
          name: "kas version check"
          command: "kas --version"

workflows:
  build-all:
    jobs:
      - build-intel