name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  rpi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clone required repos
        run: ./repo-mgr.sh init
      #- run: docker pull crops/poky:ubuntu-22.04
      - name: Run build in container
        run: docker run --rm -t -v $(pwd):/workdir crops/poky:ubuntu-22.04 --workdir=/workdir /workdir/run-build.sh
