name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  rpi:
    runs-on: ubuntu-latest
    container:
      image: crops/poky:ubuntu-22.04
      options: --user $(id -u):$(id -g)

    steps:
      #- run: /usr/bin/poky-entry.py --workdir=/__w/yald-build/yald-build
      - run: whoami
      - run: id -u
      - run: id -g
      - run: pwd
      #- uses: actions/checkout@v3
      #- name: Clone required repos
      #  run: ./repo-mgr.sh init
