name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rpi:
    runs-on: ubuntu-latest
    container: crops/yocto:ubuntu-22.04-base

    steps:
      - run: whoami
      #- uses: actions/checkout@v3
      #- name: Clone required repos
      #  run: ./repo-mgr.sh init
