name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  machine-matrix:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        machine: [raspberrypi3-64, raspberrypi2, intel-corei7-64]

    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          echo "Available storage:"
          df -h
          echo

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Clone required repos
        run: ./repo-mgr.sh init

      - name: Cache shared-state files
        uses: actions/cache@v3
        with:
          path: build/sstate-cache
          key: sstate-${{ matrix.machine }}-${{ github.run_id }}
          restore-keys: |
            sstate-${{ matrix.machine }}-
            sstate-

      - name: Run build in container
        run: |
          docker run --rm -t -v $(pwd):/workdir -e MACHINE=${{ matrix.machine }} crops/poky:ubuntu-22.04 --workdir=/workdir /workdir/run-build.sh
          find build/tmp/deploy/images/${{ matrix.machine }} -type l -delete

      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.machine }}-artifacts
          path: build/tmp/deploy/images/${{ matrix.machine }}/

      - name: Disk space report after build
        run: |
          echo "Available storage:"
          df -h
          echo
