name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  rpi:
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v6
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - uses: actions/checkout@v3
      - name: Clone required repos
        run: ./repo-mgr.sh init
      - name: Run build in container
        run: docker run --rm -t -v $(pwd):/workdir -e MACHINE=raspberrypi3-64 crops/poky:ubuntu-22.04 --workdir=/workdir /workdir/run-build.sh
