name: build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  rpi:
    runs-on: ubuntu-latest
    #container: crops/poky:ubuntu-22.04

    steps:
      - run: whoami
      - run: id -u
      - run: id -g
      - run: pwd
      #- uses: actions/checkout@v3
      #- name: Clone required repos
      #  run: ./repo-mgr.sh init
