name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rpi:
    runs-on: ubuntu-latest
    container: crops/poky:ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Clone required repos
        run: ./repo-mgr.sh init
